### ISSUE TITLE
Move plugin to Vector menu

### ISSUE THREAD

**Issue by kannes** [JanCaha/qgis-qmapshaper#2]
Right now the plugin's menu entry is in the main Plugins menu. I think would be more suitable to be in the Vector menu as it is completely focused on vector data manipulation.

![image](https://user-images.githubusercontent.com/7661092/167301509-3c06352c-7ff2-4672-868c-78e2d807e072.png)

**Comment by JanCaha** [comment]
Next version, which should be available shortly, will have the plugin listed in both menus ;-)
