### ISSUE TITLE
How to install the plugin on windows 10?

### ISSUE THREAD

**Issue by pigreco** [JanCaha/qgis-qmapshaper#3]
I am using QGIS from OSGeo4W64 v2, how to install the plugin correctly? that is, how to install mapshaper?

It's a very useful plugin, thank you so much for making it public

thank you

**Comment by JanCaha** [comment]
On windows you need to install [NODEJS](https://nodejs.org/en/docs/) and then using `npm` install `mapshaper`.

**Comment by pigreco** [comment]
I installed nodejs from OSGeo4W64:

![image](https://user-images.githubusercontent.com/7631137/168068573-dd03cf5f-bfe2-42c7-b426-25229f8cf36a.png)

I installed `mapshaper` using OSGeo4W shell:

![image](https://user-images.githubusercontent.com/7631137/168068661-32486fb9-f937-4cb1-9dac-cd537d2ab026.png)

I set the path:

![image](https://user-images.githubusercontent.com/7631137/168068772-391dc5ca-652d-445b-b9e3-00bd89055adf.png)

but the plugin doesn't work, what am I wrong?

**Comment by JanCaha** [comment]
No idea, the path in options looks correct. Could you try running `C:/OSGeo4W/apps/node/node_modules/mapshaper/bin/mapshaper` in OSGeo4W Shell to see if it actually runs the mapshaper?

**Comment by pigreco** [comment]
mapshaper doesn't seem to work;

i try to install nodejs and mapshaper directly in win.
![image](https://user-images.githubusercontent.com/7631137/168075876-7f9dc7b2-ce64-481c-b0f1-74b49d76ba09.png)

**Comment by JanCaha** [comment]
You are missing `bin` folder under `mapshaper` ... see the path in post above.

**Comment by pigreco** [comment]
> C:/OSGeo4W/apps/node/node_modules/mapshaper/bin/mapshaper

`C:\OSGeo4W\apps\node\node_modules\mapshaper\bin`  there is nothing, the folder is empty

![image](https://user-images.githubusercontent.com/7631137/168080214-94ba3894-ccd5-4cf1-a0fe-cbc52ef191ad.png)

**Comment by JanCaha** [comment]
The global install flag `-g` might change things but I have no idea where the files might be then with OSGeo4W... can you search for file `mapshaper-xl` and take a look where is it located?

**Comment by JanCaha** [comment]
Ok, then you can try to set the path in Options processing to `C:\OSGeo4W\apps\node` although I am not sure that it will work.

**Comment by pigreco** [comment]
> Ok, then you can try to set the path in Options processing to `C:\OSGeo4W\apps\node` although I am not sure that it will work.

no, it doesn't work :-(

**Comment by kannes** [comment]
Can you get any of the four things listed in your search to run in the OSGeo4W shell?

**Comment by pigreco** [comment]
> C:/OSGeo4W/apps/node/node_modules/mapshaper/bin/mapshaper

I did not understand,
can you please be more specific?

**Comment by kannes** [comment]
Sure :)

- Open the OSGeo4W and navigate to the `C:/OSGeo4W/apps/node/node_modules/mapshaper/bin/` directory, try to run `mapshaper-xl`.
- Open the OSGeo4W and navigate to the `C:/OSGeo4W/apps/node/` directory, try to run `mapshaper-xl`, `mapshaper-xl.ps1`, and `mapshaper-xl.cmd`.

**Comment by pigreco** [comment]
> `C:/OSGeo4W/apps/node/node_modules/mapshaper/bin/` directory, try to run `mapshaper-xl`.

![image](https://user-images.githubusercontent.com/7631137/168465479-2d560d00-4264-42ec-8bce-4adb85bc4bb4.png)

he writes to me:
"mapshaper-xl" is not recognized as an internal or external command, executable program or batch file

> * Open the OSGeo4W and navigate to the `C:/OSGeo4W/apps/node/` directory, try to run `mapshaper-xl`, `mapshaper-xl.ps1`, and `mapshaper-xl.cmd`.

![image](https://user-images.githubusercontent.com/7631137/168465486-44e0a7a5-e928-416e-90c7-457095978350.png)

**Comment by kannes** [comment]
The `mapshaper-xl` call from `C:/OSGeo4W/apps/node/` did work successfully so that is the directory needed in the configuration of this plugin. I see that you already tried it though without success. :(

Is there any new output printed to the shell if you launch `qgis` (I think, otherwise try `qgis-bin`) from the OSGeo4W shell and try to run the plugin?

**Comment by pigreco** [comment]
> Is there any new output printed to the shell if you launch `qgis` (I think, otherwise try `qgis-bin`) from the OSGeo4W shell and try to run the plugin?

![image](https://user-images.githubusercontent.com/7631137/168471144-17bd0a57-98c8-4a67-a58c-aaa26bcccb73.png)

the file is not generated!

**Comment by agiudiceandrea** [comment]
@pigreco, has the file `aebe8005-08c1-40e5-9a6f-f05762f67686.shp` been created in the folder `C:/Users/pigre/AppData/Local/Temp/processing_mXprtd/1b928052587f427296247f9bdd4008ec/`?

**Comment by pigreco** [comment]
@agiudiceandrea 
after execution, that file is not created.

**Comment by agiudiceandrea** [comment]
@pigreco the only way I found to let the processing algorithm to run properly is to modify the `class_qmapshaper_paths.py` file in `your_user_profile_folder\python\plugins\qmapshaper\classes\` folder changing line 31 from:
`            folder = Path(mapshaper_folder) / "bin"`
to
`            folder = Path(mapshaper_folder)# / "bin"`
and changing line 69 from:
`        return "mapshaper-xl"`
to
`        return "mapshaper-xl.cmd"`

and, after restart QGIS, setting `your_OSGeo4W_install_dir\apps\node` as the Mapshaper folder.

**Comment by JanCaha** [comment]
Hm...the next version of the plugin will have new setting "Strictly use defined Mapshaper folder", which will solve first part of the issue. The plugin will then not try to search for `bin` folder and do other heuristics for the path. 

Could any of you please take a look if the name of the command name is `mapshaper-xl.cmd` also if you install **NodeJS** and **mapshaper** as standalone applications outside of **OSGeo4W**? I could implement a switch based on **OS** to solve the second part of the issue.

Could you also try to run commands:
`npm root` 
and 
`npm list`
from OSGeo4W shell? To see to which location the npm root points and if mapshaper is correctly listed?

**Comment by pigreco** [comment]
> Could you also try to run commands:
> `npm root`
> and
> `npm list`
> from OSGeo4W shell? To see to which location the npm root points and if mapshaper is correctly listed?

![image](https://user-images.githubusercontent.com/7631137/168738877-b4160da2-bb12-4824-a79e-e411d10d77d1.png)

**Comment by agiudiceandrea** [comment]
```
run o-help for a list of available commands
C:\OSGeo4W_V2_3>npm root -g
C:\OSA194~1\apps\node\node_modules

C:\OSGeo4W_V2_3>npm list -g --depth 0
C:\OSA194~1\apps\node
+-- corepack@0.10.0
+-- mapshaper@0.5.118
`-- npm@8.3.1

```

**Comment by pigreco** [comment]
@agiudiceandrea I made the suggested changes, the algorithms launched by the processing (Convert to TopoJSON and Simplify Vector) work, but I get an error if I use the GUI:

![image](https://user-images.githubusercontent.com/7631137/168740624-1c943640-cd7b-4fe3-b38c-af3a7e5a5f34.png)

```
PermissionError: [WinError 32] Impossibile accedere al file. Il file è utilizzato da un altro processo: 'C:\\Users\\pigre\\AppData\\Local\\Temp\\processing_zzhaKa\\70133162041c4752ad6476747a620865\\81c1a394-ec18-4865-a82c-4c8e851f724c.shp' 
Traceback (most recent call last):
  File "C:\Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\CorsoBaseQGIScls2/python/plugins\qmapshaper\gui\dialog_tool_interactive_simplifier.py", line 128, in generalize_layer
    self.process.generalize_layer(simplify_percent=self.percent_spin_box.value(),
  File "C:\Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\CorsoBaseQGIScls2/python/plugins\qmapshaper\gui\interactive_simplifier_process.py", line 66, in generalize_layer
    path.unlink(missing_ok=True)
  File "C:\OSGeo4W\apps\Python39\lib\pathlib.py", line 1344, in unlink
    self._accessor.unlink(self)
PermissionError: [WinError 32] Impossibile accedere al file. Il file è utilizzato da un altro processo: 'C:\\Users\\pigre\\AppData\\Local\\Temp\\processing_zzhaKa\\70133162041c4752ad6476747a620865\\81c1a394-ec18-4865-a82c-4c8e851f724c.shp'


Versione Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versione di QGIS: 3.22.7-Białowieża Białowieża, 5a65627a 

Percorso Python:
C:\Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\CorsoBaseQGIScls2/python/plugins\qmapshaper
C:/OSGeo4W/apps/qgis-ltr/./python
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\CorsoBaseQGIScls2/python
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\CorsoBaseQGIScls2/python/plugins
C:/OSGeo4W/apps/qgis-ltr/./python/plugins
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\GDAL-3.4.3-py3.9-win-amd64.egg
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\CorsoBaseQGIScls2/python
C:\Users\pigre\AppData\Roaming\QGIS\QGIS3\profiles\CorsoBaseQGIScls2\python\plugins\kmltools\libs
D:/GitLab/consorzio_Fabre/corso_base_qgis_fabre_cls02/esercitazioni
```

**Comment by agiudiceandrea** [comment]
@pigreco I've only suggested "a simple way I found to let the processing algorithm to run properly on Windows"... I didn't tested the GUI.

**Comment by JanCaha** [comment]
Could you guys try installing testing version from [this release](https://github.com/JanCaha/qgis-qmapshaper/releases/tag/0.6.0) and let me know how it works for you? I reworked the system for guessing the paths and you can set command name to run in the Options, that should handle the problem on Windows, where you need  `mapshaper-xl.cmd` instead of just `mapshaper-xl`. All the issues mentioned here should be solved and you will get some new tools and settings as a bonus ;-)

**Comment by pigreco** [comment]
@JanCaha 
In a new profile I have installed the new plugin,
the processing algorithms work, but in the GUI this happens:
![image](https://user-images.githubusercontent.com/7631137/168859717-1029f006-1970-402b-a757-ea7241e645ff.png)

these are the settings:
![image](https://user-images.githubusercontent.com/7631137/168859913-80b0fe34-1854-4ec4-9407-7739da00e195.png)

**Comment by JanCaha** [comment]
Ok, I see. I was trying to clean the temporary files here, but it seems to cause problems. I may let them stay there and let QGIS clean the folder when closing.

**Comment by JanCaha** [comment]
I came with alternative version of handling the temporary file removal. Just one last try before I gave up and leave it to QGIS (at least on Windows). Could you try if the release 0.6.1 will solve this issue? Thanks a lot :)

**Comment by pigreco** [comment]
@JanCaha 

![image](https://user-images.githubusercontent.com/7631137/168969029-cd188e02-44a0-47d9-af58-8ddb4951b508.png)

**Comment by JanCaha** [comment]
You can try the 0.6.2 ... with that it should just skip the deletion on Windows. Hopefully QGIS will manage to remove the files after closing, otherwise the temporary folder could quickly became quite large...

**Comment by pigreco** [comment]
@JanCaha 

Seems to work fine, no error messages !!!
a thousand thanks!!!

**Comment by JanCaha** [comment]
Just look out for the size of your temp folder ;)

**Comment by JanCaha** [comment]
Would that happend event without the plugin? If it is turned off? There are some folder that QGIS creates on its own. Are those cleaned after QGIS is closed?

The plugin on itself does not create any folders, only ask QGIS to provide temporary file names and the NodeJS commands create the files.

I dont think this is releated to the plugin.

**Comment by pigreco** [comment]
I installed the 0.8.0 version of the plugin, but I still can't get it to work on Win 10 and OSGeo4W 64 QGIS 3.28
1. I installed mapshaper using ..
2. I configured the plugin with: 
![image](https://github.com/JanCaha/qgis-qmapshaper/assets/7631137/28c2ea92-96db-486b-ae47-89ba5c2b8638)

**Comment by agiudiceandrea** [comment]
@JanCaha, please update the pages https://github.com/JanCaha/qgis-qmapshaper/blob/master/README.md and https://jancaha.github.io/qgis-qmapshaper/ in order to reflect the fact that now there are two settings (not only one as stated in such pages). It should also be specified that the "Mapshaper tool name" setting must be set to `mapshaper-xl.cmd` on Windows.

**Comment by JanCaha** [comment]
:+1:  to @pigreco and @agiudiceandrea  for sorting out the issue. I just updated the the readme, website and did some internal fixing of the way the plugin was searching for NodeJS, NPM and Mapshaper. The version 0.8.2 should on windows use the correct executable name.
